v1.0.0
mercadobitcoin/mb-widgets pull request #1
Opened 2022-10-14 12:17 UTC by leandro-georges-mb-ext

2022-10-17 13:56 UTC, rogeriocosta-mb requested changes

2022-10-17 13:56 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-fixed-income-assets/mbwd-fixed-income-asset-card-list.js
> +      return `${percString}%`
Nao seria melhor dar o return logo para evitar execução de outra linha? Ou usar o "if" mesmo para leitura mais clara :)

2022-10-17 13:56 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-crypto-assets/mbwd-crypto-assets.js
> +      this.cryptoAssets.category = 'all'
Poderia tornar isso um método para ser usado genericamente em outros pontos do componente :)

2022-10-17 13:56 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-crypto-assets/mbwd-crypto-assets.js
> +    onSortChange ({ sort, order }) {
Pode ser alterado para changeSortOrder por exemplo? :)

2022-10-17 13:56 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-crypto-assets/mbwd-crypto-assets.js
> +    onPageChange (page) {
talvez "changePage"? :)

2022-10-17 13:56 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-crypto-assets/mbwd-crypto-assets.js
> +    onCategoryChange (category) {
Talvez categoryChange? :)

2022-10-17 13:56 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-crypto-assets/mbwd-crypto-assets.js
> +    'mbwd-crypto-asset-table': MBWD_CRYPTO_ASSET_TABLE()// eslint-disable-line
dúvida, precisam ser funções? :)

2022-10-17 13:56 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-crypto-assets/mbwd-crypto-assets.js
> +              <div class="view-modes" v-if="!mobileMode">
Idealmente colocar v-if no inicio do elemento para melhor visualização da lógica :)

2022-10-17 13:56 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-crypto-assets/mbwd-crypto-asset-table.js
> +                <a class="crypto-asset" v-for="asset in assets" :href="getAssetBasicTradeExperienceLink(asset.symbol)">
talvez incluir um key? :)

2022-10-17 13:56 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-crypto-assets/mbwd-crypto-asset-table.js
> +                      <div class="sorter-cell" @click="onSortChange('name')">
Acho que fica legal trocar para changeSortOrder :)

2022-10-17 13:56 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-crypto-assets/mbwd-crypto-asset-card-list.js
> +                <a v-if="!mobileMode" class="crypto-card desktop" v-for="asset in assets">
Vale colocar um :key aqui :)

2022-10-17 13:56 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-crypto-assets/mbwd-crypto-asset-card-list.js
> +                <a v-if="mobileMode" class="crypto-card mobile" v-for="asset in assets">
Val incluir um :key aqui :)

2022-10-17 13:56 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/css/mbwd-fixed-income-assets/mbwd-fixed-income-asset-card-list.scss
> +          height: 104px;
Existe alguma variação para mobile?

2022-10-17 13:56 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/css/mbwd-crypto-assets/mbwd-crypto-assets.scss
> +      font-size: 20px;
Esse valor não tem em variáveis? :)

2022-10-17 13:56 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-crypto-assets/mbwd-crypto-asset-table.js
> +                  <tr v-for="asset in assets">
Vale colocar um :key :)

2022-10-17 13:56 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-crypto-assets/mbwd-crypto-assets.js
> +                <button class="category" v-for="category in cptdAssetCategories" :class="cssIsCategoryActive(category.value)" @click="onCategoryChange(category.value)">
Vale colocar um :key :)

2022-10-17 13:56 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-fixed-income-assets/mbwd-fixed-income-asset-card-list.js
> +                <a v-if="!mobileMode" class="fixed-income-card desktop" v-for="asset in assets">
Vale colocar um :key :)

2022-10-17 13:56 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-fixed-income-assets/mbwd-fixed-income-asset-card-list.js
> +const MBWD_FIXED_INCOME_ASSET_CARD_LIST = () => ({// eslint-disable-line
Precisa ser function? Vale analisar em todos com esse caso :)

2022-10-17 13:56 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-fixed-income-assets/mbwd-fixed-income-asset-card-list.js
> +                <a v-if="mobileMode" class="fixed-income-card mobile" v-for="asset in assets">
Vale colocar um :key :)

2022-10-17 13:56 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-fixed-income-assets/mbwd-fixed-income-asset-table.js
> +                <a class="fixed-income-asset" v-for="asset in assets">
Vale colocar um :key :)

2022-10-17 13:56 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-fixed-income-assets/mbwd-fixed-income-assets.js
> +                <button class="category" v-for="category in cptdAssetCategories" :class="cssIsCategoryActive(category.value)" @click="onCategoryChange(category.value)">
Vale colocar um :key :)

2022-10-17 13:56 UTC, rogeriocosta-mb commented on widgets/mbwd-most-valued-assets/components/js/mbwd-most-valued-assets.js
> +                    <a class="asset" v-for="asset in mostValuedAssetsList" :href="getAssetBasicTradeExperienceLink(asset.symbol)">
Vale colocar um :key :)

2022-10-18 11:59 UTC, leandro-georges-mb-ext commented on widgets/mbwd-assets/components/css/mbwd-crypto-assets/mbwd-crypto-assets.scss
> +      font-size: 20px;
Não se pode usar placeholders (%some-variabe) em media queries :(

2022-10-18 12:12 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/css/mbwd-crypto-assets/mbwd-crypto-assets.scss
> +      font-size: 20px;
Não entendi :/ Eu estava sugerindo que o valor do font-size venha de variável do sass :)

2022-10-18 12:28 UTC, leandro-georges-mb-ext commented on widgets/mbwd-assets/components/css/mbwd-crypto-assets/mbwd-crypto-assets.scss
> +      font-size: 20px;
As variáveis de font-size são placeholders no SCSS e placeholder não podem ser usados em media-queries

por ex:

```
%my-typograph {
 font-size: 10px;
}

%my-typograph2 {
 font-size: 8px;
}

.my-class {
  @extend %typograph;
}


// Não pode
@media {
  .my-class {
    @extend %typograph2;
  }
}
```

2022-11-08 13:21 UTC, rogeriocosta-mb approved these changes

2022-11-09 12:35 UTC, thiagopellizzari-mb approved these changes

2022-11-09 12:55 UTC, thiagopellizzari-mb approved these changes

2022-12-19 20:08 UTC, kennedyoliveira-mb approved these changes

2022-12-19 20:59 UTC, merged