0689 Melhorias Vitrine Web não Logada
mercadobitcoin/mb-widgets pull request #16
Opened 2023-03-16 17:09 UTC by joaoaraujo-mb

**Overview:** 
Melhorias na vitrine da web não logada, alteração do default da visualização de tabela em crypto ativos e RFD e alteração do redirecionamento, landing page -> boleta
#
**Changes:** 
- Alteração do default da tabela crypto, sort por market cap ([mbwd-crypto-assets.js](https://github.com/mercadobitcoin/mb-widgets/compare/main...0689MelhoriasVitrine#diff-ccdba1cf50dcb2eeffc97f8bcc942d144a48d3a7d2acee7e7e37a6d82a6a1d6e))
- Alteração do default da tabela RFD, de Todos para Novos, sort por release date ([mbwd-fixed-income-assets.js](https://github.com/mercadobitcoin/mb-widgets/compare/main...0689MelhoriasVitrine#diff-822cec6bc2a905f72d0d6bd25a47b19d7619800c3e7a5118be6b79ba7affe14d))
- Alteração do redirecionamento do ativo, landing page --> trade experience ([mbwd-crypto-asset-table.js](https://github.com/mercadobitcoin/mb-widgets/compare/main...0689MelhoriasVitrine#diff-e7cbee44cd1b4bf9de44300c88a089e6ec609a91eb5c554590a62373144c2b25)) ([mbwd-fixed-income-asset-table.js](https://github.com/mercadobitcoin/mb-widgets/compare/main...0689MelhoriasVitrine#diff-937eb953af543552d7289e3a2c802e9292c53b4cded6ba24c8ab598765e8f577))

#
**Referências:** (Clickup, Figma e afins) 
https://app.clickup.com/t/3025236/PPMB-12808

2023-03-16 17:50 UTC, rogeriocosta-mb requested changes

2023-03-16 17:50 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-crypto-assets/mbwd-crypto-asset-table.js
> +    redirectToAssetTradeExperienceAssetCell (symbol) {
Acho que o nome aqui não precisa do `AssetCell` no sufixo, não ficou muito claro e na verdade "complicou" a leitura :) Acho que `redirectToAssetBasicTradeExperience` é suficiente em par com o uso dele da função `this.getAssetBasicTradeExperienceLink` :)

2023-03-16 17:50 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-crypto-assets/mbwd-crypto-assets.js
>        if (this.cptdIsAllCategory) {
O que seria o prefixo "cptd"? :) Se por acaso estamos usando o "td" como associação ao elemento HTML "TD", eu recomendo não usar esse pattern, o elemento pode mudar a qualquer momento, o nome deveria ser mais associado ao dado/entidade, se está em um TD, div ou qualquer outra coisa, tanto faz. Me parece que precisa mudar isso em todos com esse pattern :) Vcs já estão em um componente de contexto de "crypto", não pfecisa de "cp". entendo que o nome deve ser algo como "currentCategory" ou sendo o caso de ter uma "flag" para cada categoria, ser "currentCategoryIsAll", mas ainda acho que poderia ser um method, tipo "currentCategory() === "all" ou "isCurrentCategory('all') === true, assim se surgirem mais categorias no futuro ou trocar, não precisa ficar criando um metodo para cada :)

2023-03-16 17:50 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-fixed-income-assets/mbwd-fixed-income-asset-table.js
> +                <a class="asset" @click="redirectToAssetTradeExperienceCell(asset.product_data.symbol)">
Mesmo comentário sobre o nome do metodo aqui :)

2023-03-16 17:50 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-crypto-assets/mbwd-crypto-asset-table.js
> +    redirectToAssetTradeExperienceAssetCell (symbol) {
Além de não precisar dizer que é "cell", e se tiver que ter o mesmo link em um botão dentro de uma div? Ficaria com semântica diferente né? :)

2023-03-16 17:50 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-fixed-income-assets/mbwd-fixed-income-asset-table.js
> +    redirectToAssetTradeExperienceCell (symbol) {
Mesmo comentário sobre o nome do metodo aqui :)

2023-03-16 17:50 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-fixed-income-assets/mbwd-fixed-income-asset-table.js
>      getPercentageString (percentage = 0, marketStatus) {
Me parece que o melhor nome para esse método é "getRemainingPercentage" ou algo na linha de "getRemainingPercentageAvailable" :) PercentageString é muito genérico e soa como função global de pegar 1 percentual e transformar em string, mas me parece mais um "formatador de mensagem de disponibilidade de um percentual" :)

2023-03-16 17:50 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-fixed-income-assets/mbwd-fixed-income-asset-table.js
Sugestão de mudar o metodo getButtonClass para retornar um objeto e não string, como fazemos em todos os demais componentes por padrão, estilo:
```
      const assetsStatusToDisableButton = ['SOLD_OUT', 'FINISHED', 'FUTURE']
      return {
      'disabled': assetsStatusToDisableButton.indexOf(assetStatus) !== -1,
     'outlined': assetsStatusToDisableButton.indexOf(assetStatus) > -1
     }
```

Assim só que der "true" é retornado e muito mais estruturado para incluir mais regras sem ter que ficar alterando strings e o nome do metodo tb é muito genérico "qual button ele está pegando a class"? :) Algo como getClassesForXXXXX é importante :) Podem haver outros botões no componente etc então melhor não deixar tao genérico

2023-03-16 18:19 UTC, kennedyoliveira-mb commented on widgets/mbwd-assets/components/js/mbwd-crypto-assets/mbwd-crypto-assets.js
>        if (this.cptdIsAllCategory) {
@rogeriocosta-mb esse prefixo **cptd** é um padrão que o @leandro-georges-mb-ext havia deixado para dizer que é uma computed, como em todo canto estava usando isso seguimos o padrão.

2023-03-16 19:31 UTC, joaoaraujo-mb commented on widgets/mbwd-assets/components/js/mbwd-fixed-income-assets/mbwd-fixed-income-asset-table.js
> +                <a class="asset" @click="redirectToAssetTradeExperienceCell(asset.product_data.symbol)">
Corrigido no prox. commit

2023-03-16 19:32 UTC, joaoaraujo-mb commented on widgets/mbwd-assets/components/js/mbwd-fixed-income-assets/mbwd-fixed-income-asset-table.js
> +    redirectToAssetTradeExperienceCell (symbol) {
corrigido no prox. commit

2023-03-16 19:42 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-crypto-assets/mbwd-crypto-assets.js
>        if (this.cptdIsAllCategory) {
Entendi, minha sugestao é remover pois o computed já fica declarado no computed, senao vamso ter que falar que "methods" é methalgumacoisa": :) e assim deixamso claro o que o dado/computed ou method eh pelo nome :) @kennedyoliveira-mb

2023-03-16 19:43 UTC, joaoaraujo-mb commented on widgets/mbwd-assets/components/js/mbwd-fixed-income-assets/mbwd-fixed-income-asset-table.js
Corrigido no próximo commit, vlw Tocha, n sabia que era possível usar uma lógica dentro de um objeto dessa maneira.

2023-03-17 14:00 UTC, joaoaraujo-mb commented on widgets/mbwd-assets/components/js/mbwd-fixed-income-assets/mbwd-fixed-income-asset-table.js
> +                <a class="asset" @click="redirectToAssetTradeExperienceCell(asset.product_data.symbol)">
Esse código será revertido para seu estado anterior, a task foi modificada, não haverá alteração desse trecho :)

2023-03-17 14:00 UTC, joaoaraujo-mb commented on widgets/mbwd-assets/components/js/mbwd-crypto-assets/mbwd-crypto-asset-table.js
> +    redirectToAssetTradeExperienceAssetCell (symbol) {
Esse código será revertido para seu estado anterior, a task foi modificada, não haverá alteração desse trecho :)

2023-03-17 14:16 UTC, brunanunes-mb approved these changes

2023-03-20 14:57 UTC, joaoaraujo-mb commented on widgets/mbwd-assets/components/js/mbwd-crypto-assets/mbwd-crypto-assets.js
>        if (this.cptdIsAllCategory) {
@rogeriocosta-mb essa alteração será feita em outra branch, para que eu possa enviar para um(a) q.a testar, assim n impactar na entrega dessa task atual

2023-03-21 17:43 UTC, mateusnogueira-mb approved these changes

2023-03-21 21:08 UTC, rogeriocosta-mb requested changes

2023-03-21 21:08 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-crypto-assets/mbwd-crypto-assets.js
> +        order: 'desc',
Isso deveriam ser props com valor default e assim se desejável via tag do componente poderem ser definidas com o valor de sort e order desejado sem necessidade de alterar ou  rebuildar o componente e atualizar na CDN :) Alteração simples e poderosa que previne futuras alterações deste tipo e permitem livremente ajustar no cliente de acordo com a necessidade :)

2023-03-21 21:08 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-fixed-income-assets/mbwd-fixed-income-assets.js
> +        order: 'desc',
Mesmo ponto aqui sobre transformar em props :)

2023-03-23 12:15 UTC, joaoaraujo-mb commented on widgets/mbwd-assets/components/js/mbwd-crypto-assets/mbwd-crypto-assets.js
> +        order: 'desc',
Resolvido, alterado para props

2023-03-23 12:20 UTC, rogeriocosta-mb requested changes

2023-03-23 12:20 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-crypto-assets/mbwd-crypto-assets.js
> +    cryptoAssets: {
Acho que esta estrutura deveria ser diferente. O cryptoAssets deveria ser um data já que são dados do componente e do request e não é algo que deva vir como atributos em uma prop, já sort e order deveriam ser props separadas, pois esses sao como "configs" da tag do componente como tag do html :)

2023-03-23 12:47 UTC, joaoaraujo-mb commented on widgets/mbwd-assets/components/js/mbwd-crypto-assets/mbwd-crypto-assets.js
> +    cryptoAssets: {
Entendi Tocha, no caso apenas o sort e order seriam props, eu poderia deixar o cryptoAssets no data e o sort e order em uma única prop? ou o ideal seria os dois em separadas? tipo cryptoAssetsConfigs { sort e order aqui dentro}?

2023-03-23 13:12 UTC, joaoaraujo-mb commented on widgets/mbwd-assets/components/js/mbwd-crypto-assets/mbwd-crypto-assets.js
> +    cryptoAssets: {
`cryptoAssetsConfig: {
      type: Object,
      default () {
        return {
          sort: 'market_cap',
          order: 'desc',
        }
      }
    }
.
.
.

data () {
    return {
      intervalId: undefined,
      busy: false,
      displaySkeleton: false,
      cryptoAssets: {
        type: 'crypto',
        offset: 0,
        limit: 5,
        category: 'all',
        sort: this.cryptoAssetsConfig.sort,
        order: this.cryptoAssetsConfig.order,
        currentPage: 1,
        totalPages: 1,
        totalItems: 0,
        result: []
      },
`

2023-03-23 13:20 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-crypto-assets/mbwd-crypto-assets.js
> +    cryptoAssets: {
Você está tratando tudo como props, o cryptoAssetsConfig nao faz sentido como nome, bastam 2 props, uma para `sort` e outra para `order` nao deve ser um objeto sabe? Quer falar por slack? :) @joaoaraujo-mb

2023-03-23 13:28 UTC, joaoaraujo-mb commented on widgets/mbwd-assets/components/js/mbwd-crypto-assets/mbwd-crypto-assets.js
> +    cryptoAssets: {
`cryptoAssetsOrder: {
      type: String,
      default : 'desc'
    },
    cryptoAssetsSort: {
      type: String,
      default: 'market_cap'
    }
.
.
.

data () {
    return {
      intervalId: undefined,
      busy: false,
      displaySkeleton: false,
      cryptoAssets: {
        type: 'crypto',
        offset: 0,
        limit: 5,
        category: 'all',
        sort: this.cryptoAssetsSort,
        order: this.cryptoAssetsOrder,
        currentPage: 1,
        totalPages: 1,
        totalItems: 0,
        result: []
      },
`

2023-03-23 14:48 UTC, rogeriocosta-mb approved these changes

2023-03-23 18:36 UTC, merged