Sd 0039
mercadobitcoin/mb-widgets pull request #17
Opened 2023-03-31 20:04 UTC by joaoaraujo-mb

**Overview:** 
Remoção da visualização de cards e configuração para habilitação com feature flag
#
**Changes:** 
- Alteração do index para receber o dataset [public/index.html](https://github.com/mercadobitcoin/mb-widgets/compare/sd-0039?expand=1#diff-c2cc24bc9001b11b6add48a4cd8f893d5d6c6e4d1bd254158bd14ab997f552cd)
- Documentação do html (https://github.com/mercadobitcoin/mb-widgets/compare/sd-0039?expand=1#diff-4e498a1bc500cdf2df917c87b6569d9197892e47a142b785a3f2323c943b3e51)
- Configuração do dataset (https://github.com/mercadobitcoin/mb-widgets/compare/sd-0039?expand=1#diff-7ce063a3af9cf09ecae5b40cf396ca5b176063fd75c058e8dd40205fc9975b06)
- Validação crypto-assets (https://github.com/mercadobitcoin/mb-widgets/compare/sd-0039?expand=1#diff-ccdba1cf50dcb2eeffc97f8bcc942d144a48d3a7d2acee7e7e37a6d82a6a1d6e)
- Validação fixed-income-assets (https://github.com/mercadobitcoin/mb-widgets/compare/sd-0039?expand=1#diff-822cec6bc2a905f72d0d6bd25a47b19d7619800c3e7a5118be6b79ba7affe14d)

#
**Referências:** (Clickup, Figma e afins) 
https://app.clickup.com/t/3025236/PPMB-15167

2023-03-31 20:16 UTC, rogeriocosta-mb submitted a review, later dismissed

2023-03-31 20:16 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-fixed-income-assets/mbwd-fixed-income-assets.js
> +    displayWebMode () {
Precisa desse método? Entendo que ele é exatamente um ! displayMobileMode certo? :) não precisa del a meu ver

2023-03-31 20:21 UTC, henriquedegodoy-mb commented on widgets/mbwd-assets/components/js/mbwd-fixed-income-assets/mbwd-fixed-income-assets.js
> +    displayWebMode () {
Não é exatamente um `!displayMobileMode` pois o `displayViewMode` tem que ser `true` nos dois pois ele é pra ser o "feature flag" desse contexto, não?

2023-03-31 20:24 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-fixed-income-assets/mbwd-fixed-income-assets.js
> +    displayWebMode () {
Entao mais um motivo para estar confuso o uso de displayWebMode :) DisplayViewMode pode ter que mudar o nome para deixar mais claro o que é :) Se o o web é justamente a inversao de mobile, signfica que basta usar o `! this.mobileMode ` :) @henriquedegodoy-mb

2023-03-31 20:27 UTC, henriquedegodoy-mb commented on widgets/mbwd-assets/components/js/mbwd-fixed-income-assets/mbwd-fixed-income-assets.js
> +    displayWebMode () {
É que o `displayViewMode` é pra representar a visualização de cards e table habilitada via feature flag. Agora é para não apresentar os ícones de escolha de cards ou table.

`mobileMode` é pra apresentar os ícones numa posição da tela caso for mobile ou em outra posição caso for web.

2023-03-31 20:36 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-fixed-income-assets/mbwd-fixed-income-assets.js
> +    displayWebMode () {
Entao seria "viewModeIsTable"? :) Só destacando mobile é web tb, tipo vc acessa mobile via web, ou seja mobile ou desktop é melhor para representar o que se trata :) @henriquedegodoy-mb

2023-03-31 21:04 UTC, joaoaraujo-mb commented on widgets/mbwd-assets/components/js/mbwd-fixed-income-assets/mbwd-fixed-income-assets.js
> +    displayWebMode () {
```
displayMobileMode () {
      return this.displayViewMode && this.mobileMode
    },
    displayDesktopMode () {
      return this.displayViewMode && !this.mobileMode
    },
```

no caso do viewModeIsTable n caberia pois o displayViewMode é utilizado para "ativar/desativar" o filtro q permite a troca entre as visões de card e table,
assim passamos o displayViewMode como falso assim desativando esse switch, por isso a negação do displayMobileMode é diferente do displayDesktopMode e vai atrapalhar a lógica da feature de desativação

2023-03-31 21:18 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-fixed-income-assets/mbwd-fixed-income-assets.js
> +    displayWebMode () {
Ok, entendi o uso dele agora, obrigado :) Ainda vejo que não precisa do displayDesktopMode :)

2023-03-31 21:19 UTC, rogeriocosta-mb commented on widgets/mbwd-assets/components/js/mbwd-fixed-income-assets/mbwd-fixed-income-assets.js
> +    displayWebMode () {
exatamente pq será a inversão do this.mobileMode :) #vainafé :D

2023-04-04 12:58 UTC, kennedyoliveira-mb requested changes

2023-04-04 13:00 UTC, joaoaraujo-mb commented on widgets/mbwd-assets/components/js/mbwd-crypto-assets/mbwd-crypto-assets.js
> +    }
Opa verdade, vou fazer a correção

2023-04-04 13:48 UTC, brunanunes-mb requested changes

2023-04-04 13:48 UTC, brunanunes-mb commented on public/index.html
> +    <div id="mbwd-assets" data-lazy-loading-images="false" data-language="pt" data-track-analytics-enabled="true" data-display-view-mode="false" data-assets-domain="http://localhost:3000">
```suggestion
    <div id="mbwd-assets" data-lazy-loading-images="false" data-language="pt" data-track-analytics-enabled="true" data-display-view-mode-controls="false" data-assets-domain="http://localhost:3000">
```

2023-04-04 13:48 UTC, brunanunes-mb commented on widgets/mbwd-assets/components/js/main.js
> +      const mbwdDisplayViewMode = mbwdAssetsWrapper.dataset.displayViewModeControls ? mbwdAssetsWrapper.dataset.displayViewModeControls === 'true' : false
```suggestion
      const mbwdDisplayViewModeControls = mbwdAssetsWrapper.dataset.displayViewModeControls ? mbwdAssetsWrapper.dataset.displayViewModeControls === 'true' : false
```

2023-04-04 13:52 UTC, joaoaraujo-mb commented on widgets/mbwd-assets/README.md
> +| displayViewMode | Boolean | true | false | The display view mode defines whether the view mode will be loaded with cards and table (true) or table only (false). |
Corrigido, vlw Bruna

2023-04-05 12:50 UTC, brunanunes-mb approved these changes
LGTM 🤌

2023-04-11 14:36 UTC, joaoaraujo-mb commented on widgets/mbwd-assets/components/js/mbwd-fixed-income-assets/mbwd-fixed-income-assets.js
> +    displayWebMode () {
Resolvido :)

2023-04-11 18:18 UTC, merged